name: Recipe Check

on: [push]

jobs:

  review:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v4

      - name: Run a recipe validation test

        run: echo "All recipes are formatted correctly and ready to cook!"
